In [1]:
# Функция для шифрования текста с использованием Сцитала
def encrypt(text, columns):
    rows = (len(text) + columns - 1) // columns  # Округление вверх
    grid = [['' for _ in range(columns)] for _ in range(rows)]

    # Заполнение таблицы
    for i in range(len(text)):
        row = i // columns
        col = i % columns
        grid[row][col] = text[i]

    # Чтение по столбцам
    encrypted_text = ''
    for col in range(columns):
        for row in range(rows):
            if grid[row][col]:
                encrypted_text += grid[row][col]

    return encrypted_text

# Функция для дешифрования текста
def decrypt(encrypted_text, columns):
    rows = (len(encrypted_text) + columns - 1) // columns
    grid = [['' for _ in range(columns)] for _ in range(rows)]

    # Заполнение таблицы по столбцам
    index = 0
    for col in range(columns):
        for row in range(rows):
            if index < len(encrypted_text):
                grid[row][col] = encrypted_text[index]
                index += 1

    # Чтение по строкам
    decrypted_text = ''
    for row in range(rows):
        for col in range(columns):
            if grid[row][col]:
                decrypted_text += grid[row][col]

    return decrypted_text

# Пример использования
input_text = 'Это пример текста для шифрования с использованием Сцитала.'
columns = 5
encrypted = encrypt(input_text, columns)
decrypted = decrypt(encrypted, columns)

print('Исходный текст:', input_text)
print('Зашифрованный текст:', encrypted)
print('Дешифрованный текст:', decrypted)

Исходный текст: Это пример текста для шифрования с использованием Сцитала.
Зашифрованный текст: Эр тярииьнСлтита оясзицаоме шв поеи. екдиасовмтпрслфн ла а
Дешифрованный текст: Это рримес теклта дфя шинрова ия слиспоаьзов ниемаСцитла.п


In [2]:
# Функция для перестановки символов в группе
def permute_group(group, permutation):
    return ''.join(group[i] for i in permutation)

# Функция для обработки входной строки
def process_string(input_string, group_size=4, permutation=None):
    if permutation is None:
        # Если подстановка не задана, используем стандартную
        permutation = [0, 1, 2, 3]  # Оставляем порядок без изменений

    # Разбиваем строку на группы
    groups = [input_string[i:i + group_size] for i in range(0, len(input_string), group_size)]

    # Переставляем символы в каждой группе
    permuted_groups = [permute_group(group, permutation) for group in groups if len(group) == group_size]

    # Объединяем группы обратно в строку
    return ''.join(permuted_groups)

# Пример использования
input_text = 'Это пример текста для шифрования с использованием Сцитала.'
# Задаем подстановку (например, меняем местами 1-й и 3-й символы)
permutation = [2, 1, 0, 3]  # Пример перестановки

# Обрабатываем строку
result = process_string(input_text.replace(' ', ''), permutation=permutation)

print('Исходный текст:', input_text)
print('Результат после перестановки:', result)

Исходный текст: Это пример текста для шифрования с использованием Сцитала.
Результат после перестановки: отЭпмиреетркатсдшялиорфвинаясиспьлозавонмеиСтица


In [3]:
# Функция для выполнения маршрутной перестановки
def route_permutation(input_string, rows=5, cols=8):
    # Заполнение таблицы
    grid = [['' for _ in range(cols)] for _ in range(rows)]

    # Заполнение таблицы символами из входной строки
    index = 0
    for r in range(rows):
        for c in range(cols):
            if index < len(input_string):
                grid[r][c] = input_string[index]
                index += 1
            else:
                grid[r][c] = ' '  # Заполняем пробелами, если строка закончилась

    # Определяем маршрут для перестановки
    # Пример маршрута: сначала по диагонали, затем по строкам
    permuted_string = ''

    # Перестановка по диагонали
    for d in range(rows + cols - 1):
        for r in range(rows):
            c = d - r
            if 0 <= c < cols:
                permuted_string += grid[r][c]

    return permuted_string

# Пример использования
input_text = 'Это пример текста для шифрования с использованием Сцитала.'
# Убираем пробелы для заполнения таблицы
input_text = input_text.replace(' ', '')

# Выполняем маршрутную перестановку
result = route_permutation(input_text)

print('Исходный текст:', input_text)
print('Результат после маршрутной перестановки:', result)

Исходный текст: ЭтопримертекстадляшифрованиясиспользованиемСцитала.
Результат после маршрутной перестановки: Этротлпеяаркшноисиилмтфяьеарсздоиовсвпан


In [4]:
import numpy as np

# Функция для создания поворотной решетки
def create_grid(input_string, rows=5, cols=8):
    grid = [[' ' for _ in range(cols)] for _ in range(rows)]
    index = 0

    for r in range(rows):
        for c in range(cols):
            if index < len(input_string):
                grid[r][c] = input_string[index]
                index += 1
            else:
                break
    return grid

# Функция для шифрования текста с использованием поворотной решетки
def encrypt(input_string):
    grid = create_grid(input_string)
    encrypted_string = ''

    # Чтение по столбцам
    for c in range(len(grid[0])):
        for r in range(len(grid)):
            encrypted_string += grid[r][c]

    return encrypted_string.replace(' ', '')  # Убираем пробелы

# Функция для дешифрования текста
def decrypt(encrypted_string, rows=5, cols=8):
    grid = [[' ' for _ in range(cols)] for _ in range(rows)]
    index = 0

    # Заполнение решетки зашифрованным текстом
    for c in range(cols):
        for r in range(rows):
            if index < len(encrypted_string):
                grid[r][c] = encrypted_string[index]
                index += 1

    decrypted_string = ''

    # Чтение по строкам
    for r in range(rows):
        for c in range(cols):
            decrypted_string += grid[r][c]

    return decrypted_string.replace(' ', '')  # Убираем пробелы

# Пример использования
input_text = 'Это пример текста для шифрования с использованием поворотной решетки.'
input_text = input_text.replace(' ', '')  # Убираем пробелы для заполнения решетки

# Шифруем текст
encrypted = encrypt(input_text)
# Дешифруем текст
decrypted = decrypt(encrypted)

print('Исходный текст:', input_text)
print('Зашифрованный текст:', encrypted)
print('Дешифрованный текст:', decrypted)

Исходный текст: Этопримертекстадляшифрованиясиспользованиемповоротнойрешетки.
Зашифрованный текст: Эрлаоттянлоешиьпкиязрсфсоитривмаосаедвпн
Дешифрованный текст: Этопримертекстадляшифрованиясиспользован


In [5]:
import numpy as np

# Функция для создания шифрующей таблицы
def create_table(input_string, rows, cols):
    table = [[' ' for _ in range(cols)] for _ in range(rows)]
    index = 0

    for r in range(rows):
        for c in range(cols):
            if index < len(input_string):
                table[r][c] = input_string[index]
                index += 1
            else:
                break
    return table

# Функция для шифрования с использованием двойной перестановки
def double_permutation_encrypt(input_string, row_permutation, col_permutation):
    rows = len(row_permutation)
    cols = len(col_permutation)

    # Создаем таблицу
    table = create_table(input_string, rows, cols)

    # Первая перестановка по строкам
    permuted_rows = [''.join(table[row]) for row in row_permutation]

    # Вторая перестановка по столбцам
    encrypted_string = ''
    for col in col_permutation:
        for row in range(rows):
            encrypted_string += permuted_rows[row][col]

    return encrypted_string.replace(' ', '')  # Убираем пробелы

# Функция для дешифрования
def double_permutation_decrypt(encrypted_string, row_permutation, col_permutation):
    rows = len(row_permutation)
    cols = len(col_permutation)

    # Создаем таблицу для зашифрованного текста
    table = [[' ' for _ in range(cols)] for _ in range(rows)]

    # Заполняем таблицу зашифрованным текстом
    index = 0
    for col in col_permutation:
        for row in range(rows):
            if index < len(encrypted_string):
                table[row][col] = encrypted_string[index]
                index += 1

    # Восстанавливаем строки по первой перестановке
    decrypted_string = ''
    for row in row_permutation:
        decrypted_string += ''.join(table[row])

    return decrypted_string.replace(' ', '')  # Убираем пробелы

# Пример использования
input_text = 'Это пример текста для шифрования с использованием двойной перестановки.'
input_text = input_text.replace(' ', '')  # Убираем пробелы для заполнения таблицы

# Определяем перестановки для строк и столбцов
row_permutation = [2, 0, 1, 4, 3]  # Пример перестановки строк
col_permutation = [1, 0, 3, 2, 4, 5, 6, 7]  # Пример перестановки столбцов

# Шифруем текст
encrypted = double_permutation_encrypt(input_text, row_permutation, col_permutation)
# Дешифруем текст
decrypted = double_permutation_decrypt(encrypted, row_permutation, col_permutation)

print('Исходный текст:', input_text)
print('Зашифрованный текст:', encrypted)
print('Дешифрованный текст:', decrypted)

Исходный текст: Этопримертекстадляшифрованиясиспользованиемдвойнойперестановки.
Зашифрованный текст: яттлнлЭроаипкзяшоеьифрсосритвиомаасведнп
Дешифрованный текст: ртекстадляшифровЭтопримеаниясиспользован


In [6]:
import numpy as np

# Функция для генерации магического квадрата
def generate_magic_square(n):
    if n % 2 == 0:
        raise ValueError("Размер магического квадрата должен быть нечетным.")

    magic_square = np.zeros((n, n), dtype=int)

    num = 1
    i, j = 0, n // 2  # Начинаем с центральной верхней ячейки

    while num <= n**2:
        magic_square[i, j] = num
        num += 1
        new_i, new_j = (i - 1) % n, (j + 1) % n  # Переход вверх и вправо

        if magic_square[new_i, new_j]:  # Если ячейка занята
            i += 1  # Переход вниз
        else:
            i, j = new_i, new_j  # Переход в новую ячейку

    return magic_square

# Пример использования
n = 5  # Размер магического квадрата (нечетное число)
magic_square = generate_magic_square(n)

print("Сгенерированный магический квадрат:")
print(magic_square)

# Проверка суммы
magic_sum = np.sum(magic_square[0, :])  # Сумма первой строки
print("\nСумма каждой строки, столбца и диагонали должна быть:", magic_sum)

Сгенерированный магический квадрат:
[[17 24  1  8 15]
 [23  5  7 14 16]
 [ 4  6 13 20 22]
 [10 12 19 21  3]
 [11 18 25  2  9]]

Сумма каждой строки, столбца и диагонали должна быть: 65


In [7]:
def bit_permutation(number, permutation):
    # Преобразуем число в двоичное представление и убираем '0b' в начале
    binary_str = bin(number)[2:]

    # Дополняем до нужной длины (максимальная длина в permutation)
    max_length = max(permutation) + 1
    binary_str = binary_str.zfill(max_length)

    # Создаем новый список для перестановленных битов
    permuted_bits = ['0'] * max_length

    # Переставляем биты согласно permutation
    for i, perm_index in enumerate(permutation):
        permuted_bits[perm_index] = binary_str[i]

    # Преобразуем обратно в число
    permuted_binary_str = ''.join(permuted_bits)
    return int(permuted_binary_str, 2)

# Пример использования
number = 29  # Двоичное представление: 11101
permutation = [4, 2, 3, 0, 1]  # Пример перестановки битов

# Выполняем перестановку
result = bit_permutation(number, permutation)

print(f'Исходное число: {number} (двоичное: {bin(number)[2:]})')
print(f'Перестановка битов: {permutation}')
print(f'Результат после перестановки: {result} (двоичное: {bin(result)[2:]})')

Исходное число: 29 (двоичное: 11101)
Перестановка битов: [4, 2, 3, 0, 1]
Результат после перестановки: 15 (двоичное: 1111)
